// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 26 Sep 2017 20:00:22 MDT.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "NIDAQmx.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// DAQmxEveryNSamplesEventCallbackPtr_b317614e is a proxy for callback DAQmxEveryNSamplesEventCallbackPtr.
int DAQmxEveryNSamplesEventCallbackPtr_b317614e(void* taskHandle, int everyNsamplesEventType, unsigned int nSamples, void* callbackData);

// DAQmxDoneEventCallbackPtr_950801af is a proxy for callback DAQmxDoneEventCallbackPtr.
int DAQmxDoneEventCallbackPtr_950801af(void* taskHandle, int status, void* callbackData);

// DAQmxSignalEventCallbackPtr_97d1d041 is a proxy for callback DAQmxSignalEventCallbackPtr.
int DAQmxSignalEventCallbackPtr_97d1d041(void* taskHandle, int signalID, void* callbackData);

