// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 26 Sep 2017 20:00:22 MDT.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int DAQmxEveryNSamplesEventCallbackPtr_b317614e(void* taskHandle, int everyNsamplesEventType, unsigned int nSamples, void* callbackData) {
	return everyNSamplesEventCallbackPtrB317614E(taskHandle, everyNsamplesEventType, nSamples, callbackData);
}

int DAQmxDoneEventCallbackPtr_950801af(void* taskHandle, int status, void* callbackData) {
	return doneEventCallbackPtr950801AF(taskHandle, status, callbackData);
}

int DAQmxSignalEventCallbackPtr_97d1d041(void* taskHandle, int signalID, void* callbackData) {
	return signalEventCallbackPtr97D1D041(taskHandle, signalID, callbackData);
}

