// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 02 Dec 2016 14:10:18 MST.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package nidaqmx provides Go bindings for National Instruments NIDAQmx
*/
package nidaqmx
