// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 26 Sep 2017 20:00:22 MDT.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package nidaqmx provides Go bindings for National Instruments NIDAQmx
*/
package nidaqmx
