// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 26 Sep 2017 20:00:22 MDT.
// By https://git.io/c-for-go. DO NOT EDIT.

package nidaqmx

/*
#include "NIDAQmx.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// EveryNSamplesEventCallbackPtr type as declared in nidaqmx\NIDAQmx.h:2530
type EveryNSamplesEventCallbackPtr func(TaskHandle unsafe.Pointer, EveryNsamplesEventType int32, NSamples uint32, CallbackData unsafe.Pointer) int32

// DoneEventCallbackPtr type as declared in nidaqmx\NIDAQmx.h:2531
type DoneEventCallbackPtr func(TaskHandle unsafe.Pointer, Status int32, CallbackData unsafe.Pointer) int32

// SignalEventCallbackPtr type as declared in nidaqmx\NIDAQmx.h:2532
type SignalEventCallbackPtr func(TaskHandle unsafe.Pointer, SignalID int32, CallbackData unsafe.Pointer) int32
